#-----------------------------------------------------------------------------
# NanoSoC FPGA Targets Declaration Makefile 
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
#
# Contributors
#
# David Mapstone (d.a.mapstone@soton.ac.uk)
#
# Copyright (C) 2021-3, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------

# FPGA Specific Options - More can be added later
ifeq ($(FPGA),mps3)
	XILINX_PART  := xcku115-flvb1760-1-c
	BOARD_NAME   := arm_mps3
	PLATFORM     := bare
else ifeq ($(FPGA),zcu104)
	XILINX_PART  := xczu7ev-ffvc1156-2-e
	BOARD_NAME   := pynq_zcu104
	PLATFORM     := pynq
else # Default to MPS3
	XILINX_PART  := xcku115-flvb1760-1-c
	BOARD_NAME   := arm_mps3
	PLATFORM     := bare
endif
