ASIC_MEM_DIR 	:= $(SOCLABS_PROJECT_DIR)/memories
A53_MEM_DIR 	:= $(ASIC_MEM_DIR)/A53
A53_L2_DATA_MEM_DIR 	:= $(A53_MEM_DIR)/L2_DATA
A53_L2_TAG_MEM_DIR 		:= $(A53_MEM_DIR)/L2_TAG
A53_L2_VICT_MEM_DIR		:= $(A53_MEM_DIR)/L2_VICTIM
A53_L1_iDATA_MEM_DIR 	:= $(A53_MEM_DIR)/L1_iDATA
A53_L1_iTAG_MEM_DIR 	:= $(A53_MEM_DIR)/L1_iTAG
A53_L1_dDATA_MEM_DIR 	:= $(A53_MEM_DIR)/L1_dDATA
A53_L1_dTAG_MEM_DIR 	:= $(A53_MEM_DIR)/L1_dTAG
A53_L1_dDIRTY_MEM_DIR 	:= $(A53_MEM_DIR)/L1_dDIRTY
A53_L1_TLB_MEM_DIR 		:= $(A53_MEM_DIR)/L1_TLB
A53_L1_BTAC1_MEM_DIR 	:= $(A53_MEM_DIR)/L1_BTAC1
A53_L1_BTAC2_MEM_DIR 	:= $(A53_MEM_DIR)/L1_BTAC2
A53_L1_TAG_MEM_DIR 		:= $(A53_MEM_DIR)/L1_TAG



ASIC_IMPLEMENTATION_DIR := $(SOCLABS_PROJECT_DIR)/imp/ASIC

MEGASOC_ASIC_IMP_DIR	:= $(ASIC_IMPLEMENTATION_DIR)/megasoc
MEGASOC_FLIST_DIR 		:= $(MEGASOC_ASIC_IMP_DIR)/flist
MEGASOC_ASIC_FLIST_i	:= $(SOCLABS_PROJECT_DIR)/flist/project/top_ASIC.flist
MEGASOC_ASIC_FLIST_o	:= $(MEGASOC_FLIST_DIR)/megasoc_fc_flist.tcl

QSPI_ASIC_FLIST_i 		:= $(SOCLABS_MEGASOC_TECH_DIR)/logical/sl_ahb_qspi/flist/Top/ahb_QSPI.flist 
QSPI_ASIC_FLIST_INC		:= $(SOCLABS_PROJECT_DIR)/flist/ASIC/qspi_ASIC.flist
QSPI_ASIC_FLIST_o		:= $(MEGASOC_FLIST_DIR)/qspi_fc_flist.tcl

CA53_FLIST_i	:= $(SOCLABS_MEGASOC_TECH_DIR)/flist/IP/ARM_Cortex_A53.flist
CA53_FLIST_inc 	:= $(SOCLABS_MEGASOC_TECH_DIR)/flist/IP/ARM_CA53_ASIC.flist
CA53_FLIST_o 	:= $(MEGASOC_FLIST_DIR)/ca53_fc_flist.tcl

REPORTS_FOLDER			:= $(MEGASOC_ASIC_IMP_DIR)/reports
SYN_LOGS				:= $(MEGASOC_ASIC_IMP_DIR)/logs
NETLIST_FOLDER			:= $(MEGASOC_ASIC_IMP_DIR)/netlist/
ASIC_OUTPUT_DIR 	    := $(MEGASOC_ASIC_IMP_DIR)/outputs
ASIC_WORK_DIR 			:= $(MEGASOC_ASIC_IMP_DIR)/work
ASIC_LIBS_DIR 			:= $(MEGASOC_ASIC_IMP_DIR)/libs
ASIC_INITIAL_SYN_DIR	:= $(MEGASOC_ASIC_IMP_DIR)/initial_synthesis

A53_REPORTS_FOLDER		:= $(CA53_IMP_DIR)/reports
A53_SYN_LOGS			:= $(CA53_IMP_DIR)/logs
A53_NETLIST_FOLDER		:= $(CA53_IMP_DIR)/netlist/
A53_ASIC_OUTPUT_DIR 	:= $(CA53_IMP_DIR)/outputs
A53_ASIC_WORK_DIR 		:= $(CA53_IMP_DIR)/work
A53_ASIC_LIBS_DIR 		:= $(CA53_IMP_DIR)/libs


flist_fc_megasoc:
	@mkdir -p $(MEGASOC_FLIST_DIR)
	@(cd $(MEGASOC_FLIST_DIR) ; \
	$(SOCLABS_SOCTOOLS_FLOW_DIR)/bin/filelist_compile.py -a -t -s -d $(DEFINES_VC) -f $(MEGASOC_ASIC_FLIST_i) -i $(CA53_FLIST_inc) -o $(MEGASOC_ASIC_FLIST_o) ; \
	$(SOCLABS_SOCTOOLS_FLOW_DIR)/bin/filelist_compile.py -a -t -s -d $(DEFINES_VC) -f $(QSPI_ASIC_FLIST_i) -i $(QSPI_ASIC_FLIST_INC) -o $(QSPI_ASIC_FLIST_o) ; \
	$(SOCLABS_SOCTOOLS_FLOW_DIR)/bin/filelist_compile.py -a -t -s -f $(CA53_FLIST_i) -i $(CA53_FLIST_inc) -o $(CA53_FLIST_o) ;)


gen_a53_memories_frontend:
	@mkdir -p $(A53_MEM_DIR)
	@mkdir -p $(A53_L2_DATA_MEM_DIR)
	@mkdir -p $(A53_L2_TAG_MEM_DIR)
	@mkdir -p $(A53_L2_VICT_MEM_DIR)
	@mkdir -p $(A53_L1_iDATA_MEM_DIR)
	@mkdir -p $(A53_L1_iTAG_MEM_DIR)
	@mkdir -p $(A53_L1_dDATA_MEM_DIR)
	@mkdir -p $(A53_L1_dTAG_MEM_DIR)
	@mkdir -p $(A53_L1_dDIRTY_MEM_DIR)
	@mkdir -p $(A53_L1_TLB_MEM_DIR)
	@mkdir -p $(A53_L1_BTAC1_MEM_DIR)
	@mkdir -p $(A53_L1_BTAC2_MEM_DIR)
	@mkdir -p $(A53_L1_TAG_MEM_DIR)

megasoc_fusion_setup_dirs:
	@mkdir -p $(REPORTS_FOLDER)
	@mkdir -p $(SYN_LOGS)	
	@mkdir -p $(NETLIST_FOLDER)
	@mkdir -p $(ASIC_OUTPUT_DIR) 	 
	@mkdir -p $(ASIC_WORK_DIR) 
	@mkdir -p $(ASIC_LIBS_DIR) 
	@mkdir -p $(ASIC_INITIAL_SYN_DIR)
	cp -rf $(SOCLABS_PROJECT_DIR)/ASIC/megasoc/FusionCompiler/scripts $(MEGASOC_ASIC_IMP_DIR)/
	cp -rf $(SOCLABS_PROJECT_DIR)/ASIC/megasoc/FusionCompiler/inputs $(MEGASOC_ASIC_IMP_DIR)/
	cp -rf $(SOCLABS_PROJECT_DIR)/ASIC/megasoc/FusionCompiler/floorplan $(MEGASOC_ASIC_IMP_DIR)/

megasoc_fusion_setup_libs: megasoc_fusion_setup_dirs
	@if [ ! -d $(ASIC_LIBS_DIR)/cln16* ] ; then \
		cd $(ASIC_LIBS_DIR); lc_shell -f ../scripts/synopsys_lib_conversion.tcl ; \
	fi

a53_fusion_setup_dirs:
	@mkdir -p $(A53_REPORTS_FOLDER)
	@mkdir -p $(A53_SYN_LOGS)	
	@mkdir -p $(A53_NETLIST_FOLDER)
	@mkdir -p $(A53_ASIC_OUTPUT_DIR) 	 
	@mkdir -p $(A53_ASIC_WORK_DIR) 
	@mkdir -p $(A53_ASIC_LIBS_DIR) 
	cp -rf $(SOCLABS_PROJECT_DIR)/ASIC/CA53/FusionCompiler/scripts $(CA53_IMP_DIR)/
	cp -rf $(SOCLABS_PROJECT_DIR)/ASIC/CA53/FusionCompiler/inputs $(CA53_IMP_DIR)/
	cp -rf $(SOCLABS_PROJECT_DIR)/ASIC/CA53/FusionCompiler/floorplan $(CA53_IMP_DIR)/

a53_fusion_setup_libs: a53_fusion_setup_dirs
	@if [ ! -d $(A53_ASIC_LIBS_DIR)/cln16* ] ; then \
		cd $(A53_ASIC_LIBS_DIR); lc_shell -f ../scripts/synopsys_library_setup.tcl ; \
	fi

a53_fusion_clean_libs:
	rm -rf $(A53_ASIC_LIBS_DIR)
	@mkdir -p $(A53_ASIC_LIBS_DIR)

