#-----------------------------------------------------------------------------
# MegaSoC Regression Makefile 
# A joint work commissioned on behalf of SoC Labs, under Arm Academic Access license.
#
# Contributors
#
# Daniel Newbrook (d.newbrook@soton.ac.uk)
#
# Copyright (C) 2021-5, SoC Labs (www.soclabs.org)
#-----------------------------------------------------------------------------

# How many tests to Run In Parallel in a Regression
PARALLEL_TESTS = 4

# Regression Simulation Timeout
TIMEOUT = 60m

# Enable Coverage for Regression
COVERAGE = 1

# Create a Directory to Run a Regression in
$(eval REGRESSION_NAME =$(shell date +%Y_%m_%d_%H_%M_%S))
$(eval REGRESSION_DIR =  $(SIM_TOP_DIR)/regression_$(REGRESSION_NAME))

# Create List of Make Targets
TEST_LIST_VCS = $(shell cat $(TEST_LIST_FILE) | while read line || [ -n "$$line" ]; do echo vcs_$$line; done)

define vcs_template
.PHONY: vcs_$(1)
vcs_$(1):
	@echo Starting Test $(1)
	@$$(MAKE) regression_test_vcs TESTNAME=$(1) >> /dev/null 2>&1
	@if cat $$(REGRESSION)/$(1).log | grep " TEST PASSED "; then echo "$(1): PASSED" >> $$(REGRESSION)/RESULTS.log; elif cat $$(REGRESSION)/$(1).log | grep " TEST SKIPPED "; then echo "$(1): SKIPPED" >> $$(REGRESSION)/RESULTS.log; else echo "$(1): FAILED" >> $$(REGRESSION)/RESULTS.log; fi > /dev/null
	@echo Finished Test $(1)
endef


# Generate Targets from Templates using Test List
$(foreach TESTNAME,$(TEST_LIST), $(eval $(call vcs_template,$(TESTNAME))))

regression_test_vcs:
	@timeout $(TIMEOUT) $(MAKE) run_vcs TESTNAME=$(TESTNAME) COVERAGE=$(COVERAGE) > $(REGRESSION)/$(TESTNAME).log || true
	@if [ $(COVERAGE) = 1 ]; then cp -r $(SIM_DIR)/simv.vdb $(REGRESSION)/$(TESTNAME).vdb 2>/dev/null || true; fi


# Target to Display Regression Results on Command Line
regression_results:
	@echo --------------------------------------------
	@echo Results:
	@echo --------------------------------------------
	@python $(SOCLABS_SOCTOOLS_FLOW_DIR)/tools/regression_result.py $(REGRESSION)/RESULTS.log


# Regression Simulator Redirect
regression: regression_$(SIMULATOR)

# Create a Target for Running Simulation Regressions
regression_$(SIMULATOR):   
	@mkdir -p $(REGRESSION_DIR)
	@echo 
	@echo 
	@echo 
	@echo 
	@echo --------------------------------------------
	@echo Running Regression: $(REGRESSION_NAME)
	@echo --------------------------------------------
	@echo Simulator: $(SIMULATOR)
	@echo --------------------------------------------
	@echo $(TEST_LIST_VCS)
	@$(MAKE) -j$(PARALLEL_TESTS) all_tests_$(SIMULATOR) REGRESSION=$(REGRESSION_DIR)
	@$(MAKE) -j1 regression_results REGRESSION=$(REGRESSION_DIR)
	@if [ $(COVERAGE) = 1 ]; then $(MAKE) merge_coverage REGRESSION=$(REGRESSION_DIR); fi

merge_coverage:
	@echo --------------------------------------------
	@echo Merging Coverage Databases
	@echo --------------------------------------------
	@cd $(REGRESSION); urg -dir *.vdb -dbname merged.vdb
	@cd $(REGRESSION); urg -dir merged.vdb -report coverage_report
	@echo Coverage report generated in $(REGRESSION)/coverage_report

all_tests_vcs : $(TEST_LIST_VCS)